[versions]
androidGradlePlugin = "8.6.0"
kotlin = "2.0.20"
compose = "1.6.8"
lifecycle = "2.8.4"
material3 = "1.2.1"
media3 = "1.4.1"
room = "2.6.1"
hilt = "2.52"
ktor = "2.3.12"
ksp = "2.0.20-1.0.24"

[libraries]
guava = { group = "com.google.guava", name = "guava", version = "33.3.0-android" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version = "1.8.1" }
concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version = "1.2.0" }

gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
activity = { group = "androidx.activity", name = "activity-compose", version = "1.9.1" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.7" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version = "1.1.1" }

compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version = "1.6.8" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-animation = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "compose" }
compose-reorderable = { group = "org.burnoutcrew.composereorderable", name = "reorderable", version = "0.9.6" }
compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.6.8" }

viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version = "0.34.0" }

coil = { group = "io.coil-kt", name = "coil-compose", version = "2.7.0" }

shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version = "1.3.1" }

palette = { group = "androidx.palette", name = "palette", version = "1.0.0" }

media3 = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

apache-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.17.0" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

brotli = { group = "org.brotli", name = "dec", version = "0.1.2" }

desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.1" }

junit = { group = "junit", name = "junit", version = "4.13.2" }

timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }